# =========================================================
# NETLIFY SECURITY CONFIG
# =========================================================

[[redirects]]
  from = "/*"
  to = "/:splat"

  [redirects.rate_limit]
    window_limit = 120
    window_size = 60
    aggregate_by = ["ip", "domain"]